// flow-typed signature: 526a8125bba99d4961207b3fbba50759
// flow-typed version: <<STUB>>/eslint-plugin-react-refresh_v^0.4.3/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-refresh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-refresh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-react-refresh/index' {
  declare module.exports: $Exports<'eslint-plugin-react-refresh'>;
}
declare module 'eslint-plugin-react-refresh/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-refresh'>;
}
