// flow-typed signature: c4fe01d7f4e689c1b83b72512250c4bf
// flow-typed version: <<STUB>>/react-grid-gallery_v^1.0.1-alpha.0/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-grid-gallery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-grid-gallery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-grid-gallery/dist/react-grid-gallery.cjs' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/dist/react-grid-gallery.esm' {
  declare module.exports: any;
}

declare module 'react-grid-gallery/dist/react-grid-gallery.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-grid-gallery/dist/react-grid-gallery.cjs.js' {
  declare module.exports: $Exports<'react-grid-gallery/dist/react-grid-gallery.cjs'>;
}
declare module 'react-grid-gallery/dist/react-grid-gallery.esm.js' {
  declare module.exports: $Exports<'react-grid-gallery/dist/react-grid-gallery.esm'>;
}
declare module 'react-grid-gallery/dist/react-grid-gallery.umd.js' {
  declare module.exports: $Exports<'react-grid-gallery/dist/react-grid-gallery.umd'>;
}
