// flow-typed signature: 37f16cb92bfa83c909ebb9c496c736ce
// flow-typed version: <<STUB>>/vite-plugin-require-transform_v^1.0.21/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-require-transform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-require-transform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite-plugin-require-transform/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite-plugin-require-transform/dist/index' {
  declare module.exports: $Exports<'vite-plugin-require-transform/dist'>;
}
declare module 'vite-plugin-require-transform/dist/index.js' {
  declare module.exports: $Exports<'vite-plugin-require-transform/dist'>;
}
