// flow-typed signature: ad7f4c179e69c25a22022e18fd03c4bb
// flow-typed version: <<STUB>>/vite-require_v^0.2.3/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite-require/dist/analyze' {
  declare module.exports: any;
}

declare module 'vite-require/dist/dynamic-require' {
  declare module.exports: any;
}

declare module 'vite-require/dist' {
  declare module.exports: any;
}

declare module 'vite-require/dist/types' {
  declare module.exports: any;
}

declare module 'vite-require/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite-require/dist/analyze.js' {
  declare module.exports: $Exports<'vite-require/dist/analyze'>;
}
declare module 'vite-require/dist/dynamic-require.js' {
  declare module.exports: $Exports<'vite-require/dist/dynamic-require'>;
}
declare module 'vite-require/dist/index' {
  declare module.exports: $Exports<'vite-require/dist'>;
}
declare module 'vite-require/dist/index.js' {
  declare module.exports: $Exports<'vite-require/dist'>;
}
declare module 'vite-require/dist/types.js' {
  declare module.exports: $Exports<'vite-require/dist/types'>;
}
declare module 'vite-require/dist/utils.js' {
  declare module.exports: $Exports<'vite-require/dist/utils'>;
}
