// flow-typed signature: 113e530966932f8882643e1f6e20a213
// flow-typed version: <<STUB>>/vite-plugin-require_v^1.1.11/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite-plugin-require/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite-plugin-require/dist/index' {
  declare module.exports: $Exports<'vite-plugin-require/dist'>;
}
declare module 'vite-plugin-require/dist/index.js' {
  declare module.exports: $Exports<'vite-plugin-require/dist'>;
}
