// flow-typed signature: 4e18d3ce87a146d35be58a436d338fba
// flow-typed version: <<STUB>>/vite-jsconfig-paths_v^2.0.1/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-jsconfig-paths'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-jsconfig-paths' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite-jsconfig-paths/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite-jsconfig-paths/dist/index' {
  declare module.exports: $Exports<'vite-jsconfig-paths/dist'>;
}
declare module 'vite-jsconfig-paths/dist/index.js' {
  declare module.exports: $Exports<'vite-jsconfig-paths/dist'>;
}
