// flow-typed signature: abbefbd095539a03b28c40482e674c51
// flow-typed version: <<STUB>>/@types/react_v^18.2.15/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
