// flow-typed signature: 579a970b940f00e9a31155135f0e42f6
// flow-typed version: <<STUB>>/@types/react-dom_v^18.2.7/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
